// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YieldDataLogger.Api.Data;

#nullable disable

namespace YieldDataLogger.Api.Data.Migrations
{
    [DbContext(typeof(YieldDbContext))]
    [Migration("20260421091635_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YieldDataLogger.Api.Data.Entities.InstrumentEntity", b =>
                {
                    b.Property<string>("CanonicalSymbol")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Category")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CnbcSymbol")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("InvestingPid")
                        .HasColumnType("int");

                    b.HasKey("CanonicalSymbol");

                    b.HasIndex("CnbcSymbol")
                        .IsUnique()
                        .HasFilter("[CnbcSymbol] IS NOT NULL");

                    b.HasIndex("InvestingPid")
                        .IsUnique()
                        .HasFilter("[InvestingPid] IS NOT NULL");

                    b.ToTable("Instruments", (string)null);
                });

            modelBuilder.Entity("YieldDataLogger.Api.Data.Entities.PriceTickEntity", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<double>("TsUnix")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Symbol", "TsUnix");

                    b.ToTable("PriceTicks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
